# .readthedocs.yaml

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py  # Path to the Sphinx config file (adjust if needed)

# Python settings
python:
  version: "3.10"  # Specify the Python version (can be 3.7, 3.8, 3.9, etc.)
  install:
    - requirements: docs/requirements.txt  # List of dependencies for your docs

# Build settings
# formats:
#   - html
  # - pdf  # Optional, if you want PDF generation
